resolver: lts-12.26

packages:
- .

extra-deps:
  # Last commit to master as 2019-01-29
- git: git@github.com:input-output-hk/plutus.git
  commit: ec79bdacd45cdae051b70719e86d5149ab190444
  subdirs:
    - language-plutus-core
    - plutus-tx
    - plutus-core-interpreter
    - plutus-ir
    - wallet-api
    - plutus-playground-lib
    - marlowe

- git: https://github.com/input-output-hk/cardano-crypto.git
  commit: 3c5db489c71a4d70ee43f5f9b979fcde3c797f2a

- serialise-0.2.1.0
- hint-0.9.0
